name: weather_pet
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  # dio: ^5.4.0
  json_annotation: ^4.8.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rxdart: ^0.27.7
  local_storage_tracking_locations_api:
    path: "packages/local_storage_tracking_locations_api"
  local_storage_settings_api:
    path: "packages/local_storage_settings_api"
  weather_repository:
    path: "packages/weather_repository"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - lib/domain/resources/weather/64x64/day/
    - lib/domain/resources/weather/64x64/night/
